CREATE TABLE IF NOT EXISTS squadra (
    ID INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Forza INT NOT NULL,
    ID_Campionato INT NOT NULL,
    PRIMARY KEY (ID, ID_Campionato),
    FOREIGN KEY (ID_Campionato) REFERENCES campionato(ID)
);

INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1','Manchester City','1180','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2','Arsenal','1090','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3','Chelsea','925','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4','Manchester United','882','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5','Liverpool','830','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6','Tottenham','689','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7','Newcastle','598','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8','Aston Villa','597','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9','West Ham','443','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10','Nottingham','381','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11','Brighton','376','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12','Brentford','365','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13','Everton','339','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14','Bournemouth','337','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15','Crystal Palace','333','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16','Fulham','295','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17','Wolves','289','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18','Burnley','227','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('19','Sheffield','135','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('20','Luton Town','85','1');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Real Madrid', '991', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Barcellona', '814', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Atletico Madrid', '442', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Real Sociedad', '397', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Siviglia', '209', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Villarreal', '209', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Betis', '209', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Athletic Bilbao', '202', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Valencia', '147', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Osasuna', '137', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Celta Vigo', '125', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Girona', '125', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Getafe', '125', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Mallorca', '101', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Almeria', '99', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Rayo Vallecano', '91', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Cadiz', '64', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Granada', '64', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('19', 'Alaves', '51', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('20', 'Las Palmas', '49', '2');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Genoa', '805', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Napoli', '577', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Milan', '529', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Inter', '523', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Juventus', '433', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Roma', '381', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Atalanta', '304', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Lazio', '284', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Fiorentina', '246', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Torino', '175', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Bologna', '159', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Sassuolo', '155', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Udinese', '147', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Sampdoria', '100', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Monza', '95', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Empoli', '92', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Verona', '80', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Lecce', '74', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('19', 'Cagliari', '63', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('20', 'Frosinone', '54', '3');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Bayern Monaco', '897', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Borussia Dortmund', '467', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Bayer Leverkusen', '446', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Lipsia', '403', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Wolfsburg', '236', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Union Berlino', '192', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Borussia M Gladbach', '192', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Eintracht Francoforte', '170', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Friburgo', '164', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Hoffenheim', '151', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Augusta', '120', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Stoccarda', '116', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Mainz', '109', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Colonia', '96', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Werder Brema', '91', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Bochum', '55', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Darmstadt', '32', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Heidenheim', '29', '4');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Feyenoord', '204', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'PSV', '187', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Ajax', '179', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'AZ Alkmaar', '79', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Utrecht', '46', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Twente', '44', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Heerenveen', '32', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Vitesse', '27', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'NEC Nijmegen', '24', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Sparta Rotterdam', '24', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Excelsior', '19', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Sittard', '19', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Almere City', '14', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Eagles Deventer', '14', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Zwolle', '13', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Almelo', '13', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Waalwijk', '11', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Volendam', '10', '5');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'PSG', '1030', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Monaco', '331', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Rennes', '269', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Marsiglia', '257', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Nizza', '228', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Lille', '207', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lens', '198', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Lione', '196', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Nantes', '110', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Strasburgo', '101', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Lorient', '92', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Montpellier', '87', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Reims', '87', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Brestois', '65', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Tolosa', '64', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Clermont', '51', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Havre', '49', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Metz', '34', '6');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Benfica', '344', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Porto', '282', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Sporting', '240', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Braga', '124', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Famalicao', '43', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Vitoria Guimaraes', '37', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Boavista', '21', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Arouca', '20', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Estoril', '19', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Vicente', '19', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Moreirense', '15', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Vizela', '15', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Portimonense', '14', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Chaves', '14', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Rio Ave', '13', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Casa Pia', '12', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Farense', '11', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Estrela Amadora', '10', '7');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Bruges', '121', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Genk', '112', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Royal Antwerp', '98', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Anderlecht', '91', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Gent', '79', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Standard Liegi', '57', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'St. Gilloise', '35', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Charleroi', '35', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Westerlo', '33', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'OH Leuven', '29', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Cercle Brugge', '28', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Kortrijk', '25', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Eupen', '24', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Mechelen', '24', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Molenbeek', '21', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Sint-Truiden', '13', '8');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Galatasaray', '239', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Fenerbahce', '205', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Trabzonspor', '129', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Besiktas', '128', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Basaksehir', '67', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Adana Demirspor', '47', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Samsunspor', '37', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Antalyaspor', '35', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Konyaspor', '33', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Ankaragucu', '32', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Pendikspor', '29', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Alanyaspor', '29', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Kayserispor', '27', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Caykur Rizespor', '27', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Karagumruk', '26', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Gaziantep', '24', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Sivasspor', '19', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Kasimpasa', '18', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('19', 'Hatayspor', '18', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('20', 'Istanbulspor', '13', '9');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Celtic', '121', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Rangers', '107', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Aberdeen', '16', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Midlothian', '15', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Hibernian', '12', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Ross Country', '8', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Livingston', '8', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Mirren', '7', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'St. Johnstone', '7', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Dundee', '6', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Motherwell', '6', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Kilmarnock', '6', '10');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Salisburgo', '206', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Graz', '51', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Rapid Vienna', '30', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Lask', '28', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Austria Vienna', '18', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Wolfsberger', '13', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lustenau', '10', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Klagenfurt', '9', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Hartber', '9', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Tirol', '9', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Altach', '8', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'BWL', '6', '11');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Young Boys', '56', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Basilea', '34', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Servette', '27', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Lucerna', '26', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'San Gallo', '24', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Lugano', '24', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lausanne Sport', '20', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Grasshopper', '16', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Zurigo', '15', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Lausanne Ouchy', '13', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Yverdon', '11', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Winterthur', '10', '12');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Stella Rossa', '71', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Partizan', '33', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Topola', '21', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Cukaricki', '21', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Vojvodina', '14', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Subotica', '10', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Pancevo', '8', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Kragujevac', '8', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Radnicki', '7', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Vozdovac', '7', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Pazar', '7', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'IMT', '6', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Napredak', '6', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Javor-Matis', '6', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Radnik', '5', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Mladost', '3', '13');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Copenaghen', '66', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Midtjylland', '41', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Nordsjaelland', '37', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Brondby', '33', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Aarhus', '17', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Viborg', '12', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Randers', '12', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Odense', '12', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Silkeborg', '11', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Lyngby', '8', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Vejle', '8', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Hvidovre', '6', '14');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Bodo/Glimt', '37', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Rosenborg', '21', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Molde', '21', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Viking', '19', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Brann', '13', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Valerenga', '13', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lillestrom', '12', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Tromso', '10', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Sarpsborg', '9', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Odds', '9', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Haugesund', '8', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Stabaek', '8', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Aalesund', '7', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Stromsgodset', '7', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Hamarkameratene', '6', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Sandefjord', '6', '15');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Sparta Praga', '44', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Slavia Praga', '43', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Plzen', '29', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Banik', '11', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Slovacko', '9', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Olomouc', '8', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Liberec', '8', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Jablonec', '8', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Pardubice', '7', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Bohemians Praga', '7', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Mlada Boleslav', '7', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Teplice', '6', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Kralove', '6', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Budejovice', '6', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Karvina', '6', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Zlin', '5', '16');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Maccabi Haifa', '20', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Maccabi Tel Aviv', '17', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Beer Sheva', '14', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Netanya', '9', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Ashdod', '8', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Beitar', '8', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Hapoel Tel Aviv', '7', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Ihud Bnei', '6', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Hapoel Haifa', '6', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Jerusalem', '6', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Maccabi Petah Tikva', '6', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Bnei Reineh', '5', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Hadera', '4', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Hapoel Petah Tikva', '4', '17');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Shakhtar', '106', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Dinamo Kiev', '54', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Dnipro', '21', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Zorya', '15', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Vorskla', '10', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Rukh Lviv', '10', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Kolos kKovalivka', '10', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Polissya', '9', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Rig', '8', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Oleksandriya', '8', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Kharkiv', '7', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Odessa', '7', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Cherkasy', '7', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Rivne', '6', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Minaj', '6', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Obolon Kyiv', '5', '18');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Olympiakos', '104', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'AEK', '67', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'PAOK', '64', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Panathinaikos', '55', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Aris', '27', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Atromitos', '17', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Volos', '12', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Creta', '11', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Panetolikos', '10', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Asteras', '10', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Giannina', '9', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Lamia', '9', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Panserraikos', '8', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Kifisias', '7', '19');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Dinamo Zagabria', '79', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Hajduk Spalato', '50', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Rijeka', '23', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Osijek', '17', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Lokomotiva Zagreb', '11', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Varazdin', '10', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Gorica', '10', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Istra', '8', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Rudes', '7', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Slaven Belupo', '6', '20');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Rakow Czestochowa', '39', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Legia Varsavia', '36', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Lech Poznan', '32', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Zaglebie Lubin', '15', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Cracovia', '13', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Pogon Szczecin', '13', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Piast Gliwice', '11', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Jagiellonia Bialystok', '11', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Widzew Lodz', '10', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Górnik Zabrze', '10', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Slask Wroclaw', '10', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Warta Poznan', '10', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Radomiak Radom', '9', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Korona Kielce', '8', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Ruch Chorzow', '7', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'LKS Lodz', '7', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('17', 'Puszcza Niepolomice', '6', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('18', 'Stal Mielec', '5', '21');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Malmo', '31', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'BK Hacken', '26', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Hammarby', '21', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Elfsborg', '17', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Solna', '17', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Djurgardens', '16', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Norrkoping', '14', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Goteborg', '13', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Mjällby', '10', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Brommapojkarna', '10', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Kalmar', '10', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Sirius', '10', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Varnamo', '8', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Degerfors', '7', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Halmstads', '7', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Varbergs', '5', '22');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'FCSB', '29', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Farul Constanta', '19', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Universitatea Craiova', '19', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Rapid', '16', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'CFR Cluj', '15', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Gheorghe', '14', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Universitatea Cluj', '12', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'U Craiova', '11', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Hermannstadt', '9', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Voluntari', '9', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Petrolul Ploiesti', '8', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Botosani', '8', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Arad', '7', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Politehnica Iasi', '5', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Dinamo', '5', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Otelul Galati', '5', '23');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Pafos', '27', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Aris Limassol', '17', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Omonia Nicosia', '17', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Larnaca', '15', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Limassol', '15', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'APOEL', '13', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Anorthosis', '13', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'AEL Limassol', '8', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Nea Salamis', '7', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Pano Polemidion', '6', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Ethnikos Achnas', '4', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Doxa Katokopias', '4', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Othellos Athienou', '2', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Zakakiou', '2', '24');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Ferencvarosi', '48', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Fehérvár', '11', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Puskas Akademia', '10', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Debreceni', '9', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Kisvárda', '7', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Kecskeméti', '7', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Diósgyőri', '7', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Újpest', '7', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Budapest', '6', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Paksi', '6', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Mezokovesd', '6', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Zalaegerszegi', '6', '25');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Zenit', '153', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Spartak Mosca', '101', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Krasnodar', '81', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'CSKA Mosca', '79', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Dinamo Mosca', '74', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Lokomotiv Mosca', '72', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Rostów', '46', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Sovetov Samara', '30', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Grozny', '29', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Rubin Kazan', '26', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Sochi', '23', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Orenburg', '22', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Ekaterinburg', '18', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Kaliningrad', '16', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Nizhniy Novgorod', '15', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Voronezh', '10', '26');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Ludogorets', '39', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Levski Sofia', '22', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'CSKA Sofia', '21', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'CSKA', '17', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Botev Plovdiv', '11', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Kardzhali', '8', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lokomotiv Plovdiv', '8', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Cherno More Varna', '7', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Slavia Sofia', '5', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Veliko Tarnovo', '5', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Lokomotiv Sofia', '4', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Krumovgrad', '4', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Pazardzhik', '4', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Botev Vratsa', '4', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Blagoevgrad', '3', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Stara Zagora', '3', '27');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Slovan Bratislava', '15', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Dunajska Streda', '12', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Spartak Trnava', '8', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Zilina', '6', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Ruzomberok', '5', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Kosice', '4', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Trencin', '4', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Podbrezova', '4', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Banska Bystrica', '4', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Michalovce', '4', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Skalica', '3', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Moravce-Vrable', '3', '28');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Neftci Baku', '16', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Qarabag', '13', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Sabah', '13', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Zira', '7', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Turan-Tovuz', '6', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Sumqayit', '6', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Qabala', '5', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Sabail', '4', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Nakchivan', '3', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Kapaz', '3', '29');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Sheriff Tiraspol', '12', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Petrocub Hîncești', '4', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Milsami Orhei', '3', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Zimbru Chisinau', '3', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Floresti', '1', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Bălți', '1', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Dacia Buiucani', '1', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Selemet', '1', '30');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Olimpia Lubiana', '13', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Maribor', '8', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Celje', '7', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Koper', '5', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Mura', '5', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Domzale', '4', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Radomlje', '4', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Rogaska', '3', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Bravo', '3', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Aluminij', '2', '31');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Shamrock Rovers', '3', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Derry City', '3', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'St. Patrick s', '3', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Dundalk', '2', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Sligo Rovers', '2', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Bohemians', '2', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Cork City', '2', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Shelbourne', '1', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'University Dublin', '1', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Drogheda', '1', '32');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Ballkani', '5', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Drita', '3', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Llapi', '3', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Prishtina', '2', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Dukagjini', '2', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Gjilani', '2', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Malisheva', '2', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Feronikeli', '1', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Liria Prizren', '1', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Fushe Kosova', '1', '33');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Astana', '14', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Ordabasy', '11', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Aktobe', '9', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Kairat Almaty', '6', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Tobol Kostanay', '6', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Aksu', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Shakhter Karaganda', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Petropavlovsk', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Atyrau', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Maktaaral', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Taldykorgan', '4', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Kaspiy Aktau', '3', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Kokshetau', '3', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Kyzylorda', '3', '34');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Riga', '12', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'RFS', '7', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Valmiera', '4', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Auda', '4', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Liepaja', '3', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Metta', '1', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Daugavpils', '1', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Tukums', '1', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Jelgava', '1', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Super Nova', '1', '35');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Urartu Yerevan', '6', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Pyunik Erevan', '5', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Noah Yerevan', '5', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Alashkert Yerevan', '4', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Ararat-Armenia', '4', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'BKMA Yerevan', '2', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Ararat Erewan', '2', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Shirak Gyumri', '2', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Van', '2', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'West Armenia', '2', '36');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Helsinki', '8', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Kuopion Palloseura', '5', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Honka', '5', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Seinäjoki', '3', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Inter Turku', '3', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Oulu', '3', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Lahti', '3', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Vaasan Palloseura', '3', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Ilves Tampere', '2', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Mariehamn', '2', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Haka', '2', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'KTP', '2', '37');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Vaduz', '5', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Eschen', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Balzers', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Triesen', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Ruggell', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Triesenberg', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Schaan', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Gamprin', '1', '38');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Zrinjski Mostar', '10', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Sarajevo', '8', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Borac Banja Luka', '6', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Siroki Brijeg', '5', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Velez Mostar', '5', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Zeljeznicar Sarajevo', '4', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Tuzla City', '3', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Zvijezda', '3', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Sloga Meridian', '3', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'GOSK Gabela', '3', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Posusje', '3', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Igman Konjic', '2', '39');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Klaksvik', '2', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'HB Torshavn', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Torshavn', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Vikingur', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Streymur', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Vestur', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Toftir', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Fuglafjordur', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Argir', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Tvøroyri', '1', '40');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Breidablik Kópavogur', '2', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Víkingur Reykjavík', '2', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Valur Reykjavík', '2', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Akureyri', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Reykjavík', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Hafnarfjördur', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Stjarnan Gardabaer', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Vestmannaeyjar', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Fram Reykjavík', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Keflavík', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Kópavogs', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Fylkir Reykjavík', '1', '41');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Larne FC', '3', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Cliftonville FC', '3', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Glentoran FC Belfast', '3', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Linfield FC', '2', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Crusaders FC', '2', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Coleraine FC', '2', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Carrick Rangers', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Glenavon FC', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Dungannon Swifts', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Newry City AFC', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Ballymena United', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Loughgall FC', '1', '42');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Swift Hesperange', '5', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Titus Petange', '2', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Progrès Niederkorn', '2', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Differdange 03', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Dudelange', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Jeunesse Esch', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Mondorf-Les-Bai', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Victoria Rosport', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'UNA Strassen', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Wiltz 71', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Käerjeng 97', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Union Luxembourg', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Fola Esch', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Mondercange', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Schifflange 95', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'Marisca Mersch', '1', '43');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Zalgiris Vilnius', '8', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Hegelmann', '5', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Kauno Zalgiris', '5', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Panevezys', '5', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Siauliai', '4', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Riteriai', '4', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Banga Gargzdai', '3', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Dainava Alytus', '2', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Dziugas Telsiai', '2', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Suduva Marijampole', '2', '44');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Hamrun Spartans', '4', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Floriana', '4', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Birkirkara', '3', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Hibernians', '3', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Balzan', '2', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Gzira United', '2', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Marsaxlokk', '2', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Mosta', '2', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Valletta', '2', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Gudja United', '1', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Santa Lucia', '1', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Sliema Wanderers', '1', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Sirens', '1', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Naxxar Lions', '1', '45');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Dinamo Tbilisi', '6', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Dinamo Batumi', '6', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Saburtalo', '5', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Torpedo Kutaisi', '4', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Samgurali Tskaltubo', '4', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Telavi', '3', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Dila Gori', '3', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Gagra', '2', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Samtredia', '2', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Shukura Kobuleti', '1', '46');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Partizani', '5', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Tirana', '5', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Egnatia', '4', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Vllaznia', '3', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Dinamo City', '3', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Teuta', '3', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Erzeni', '2', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Skënderbeu', '2', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Kukësi', '2', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Laçi', '1', '47');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Flora Tallinn', '4', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Levadia', '3', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Paide Linnameeskond', '3', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Kalju', '3', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Kuressaare', '2', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Trans Narva', '1', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Kalev Tallinn', '1', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Pärnu Vaprus', '1', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Tammeka', '1', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Harju Laagri', '1', '48');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Dinamo Minsk', '7', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'BATE Borisov', '6', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Torpedo Zhodino', '5', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Neman Grodno', '5', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Slavia Mozyr', '4', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Shakhter Soligorsk', '3', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Gomel', '3', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Isloch Minsk', '3', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Slutsk', '3', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Dynamo Brest', '2', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Naftan Novopolotsk', '2', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Minsk', '2', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Energetik', '2', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Smorgon', '2', '49');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Shkendija Tetovo', '5', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Shkupi', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Struga Trim & Lum', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Rabotnicki Skopje', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'AP Brera', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Gostivar', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Sileks Kratovo', '3', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Gjorce Petrov', '2', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Bregalnica Stip', '2', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Tikves Kavadarci', '2', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Voska Sport', '1', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Vardar Skopje', '1', '50');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Inter d''Escaldes', '3', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Santa Coloma', '2', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Atlètic d''Escaldes', '3', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Penya Encarnada', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Santa Coloma', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Ordino', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Pas de la Casa', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Esperança d''Andorra', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Atlètic Amèrica', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Carroi', '1', '51');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'The New Saints', '2', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Connah''s Quay Nomads', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Haverfordwest County', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Penybont', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Bala Town', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Pontypridd United', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Barry Town United', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Cardiff University', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Caernarfon Town', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Newtown', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'Colwyn Bay', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Aberystwyth Town', '1', '52');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Sutjeska Niksic', '3', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'Decic Tuzi', '3', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Buducnost Podgorica', '2', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Bijelo Polje', '2', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Petrovac', '2', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Mornar Bar', '1', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Arsenal Tivat', '1', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Donja Gorica', '1', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Jezero', '1', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Rudar Pljevlja', '1', '53');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Lincoln Red Imps', '2', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'St Joseph''s', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Bruno''s Magpies', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Mons Calpe', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Manchester 62', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Lynx', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Europa', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Lions Gibraltar', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'College 1975', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Europa Point', '1', '54');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('1', 'Tre Penne', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('2', 'La Fiorita', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('3', 'Virtus Acquaviva', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('4', 'Cosmos', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('5', 'Tre Fiori', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('6', 'Libertas', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('7', 'Murata', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('8', 'Fiorentino', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('9', 'Juvenes/Dogana', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('10', 'Folgore/Falciano', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('11', 'San Giovanni', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('12', 'Domagnano', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('13', 'Cailungo', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('14', 'Faetano', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('15', 'Pennarossa', '1', '55');
INSERT INTO `squadra`(`ID`, `Nome`, `Forza`, `ID_Campionato`) VALUES ('16', 'San Marino Academy', '1', '55');